#!/bin/bash

# Look for timeout lines, and run them.  Then take the output and update
# layout.6.all for each line of output.  (This update MUST be sequential to
# avoid sed reading a partial file and truncating the output.)
while grep -q Timeout layout.6.all; do
  cat layout.6.all | grep Timeout | head -n1 | while read a b c d e f g rest; do
    layout="$a $b $c $d $e $f $g"
    echo Starting $layout
    sed "/^$layout/ s#.*#$layout Working#" -i layout.6.all
    time nice -n19 ./layout6stable $layout |
      xargs -I {} sed "/^$layout/ s#.*#{}#" -i layout.6.all
  done

done
